services:
  - type: web
    name: telemarketing-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_7.py --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
